// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAc3EWof_aSdz630baAkq1dPlD5S_dyeeE',
    appId: '1:800301662832:web:8caf3e3aa8e564e7876ab5',
    messagingSenderId: '800301662832',
    projectId: 'viaamigo-9fea7',
    authDomain: 'viaamigo-9fea7.firebaseapp.com',
    storageBucket: 'viaamigo-9fea7.firebasestorage.app',
    measurementId: 'G-5TZGD0QMBD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnQ-wY0StBaJH22qksYzdiSUsl-5ISHYo',
    appId: '1:800301662832:android:309970bbf1a1107d876ab5',
    messagingSenderId: '800301662832',
    projectId: 'viaamigo-9fea7',
    storageBucket: 'viaamigo-9fea7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqd-6CmTTpRqN8VpK1TrQm1g2dLSVPCuw',
    appId: '1:800301662832:ios:612dbf5446f64801876ab5',
    messagingSenderId: '800301662832',
    projectId: 'viaamigo-9fea7',
    storageBucket: 'viaamigo-9fea7.firebasestorage.app',
    iosBundleId: 'com.example.viaamigo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqd-6CmTTpRqN8VpK1TrQm1g2dLSVPCuw',
    appId: '1:800301662832:ios:612dbf5446f64801876ab5',
    messagingSenderId: '800301662832',
    projectId: 'viaamigo-9fea7',
    storageBucket: 'viaamigo-9fea7.firebasestorage.app',
    iosBundleId: 'com.example.viaamigo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAc3EWof_aSdz630baAkq1dPlD5S_dyeeE',
    appId: '1:800301662832:web:4e7f8455d785e311876ab5',
    messagingSenderId: '800301662832',
    projectId: 'viaamigo-9fea7',
    authDomain: 'viaamigo-9fea7.firebaseapp.com',
    storageBucket: 'viaamigo-9fea7.firebasestorage.app',
    measurementId: 'G-NNTZM9LYH2',
  );

}