name: viaamigo
description: "A new Flutter project."

# Empêche la publication sur pub.dev (utile pour les projets privés)
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  # UI & Animations
  cupertino_icons: ^1.0.8
  flex_color_scheme: ^8.1.1
  animations: ^2.0.11
  auto_size_text: ^3.0.0
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.17
  badges: ^3.1.2
  font_awesome_flutter: ^10.8.0
  smooth_page_indicator: ^1.2.0+3
  liquid_swipe: ^3.1.0
  flutter_native_splash: ^2.4.4

  # Authentification
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  google_sign_in: ^6.3.0
  sign_in_with_apple: ^7.0.1
  flutter_facebook_auth: ^7.1.2
  flutter_secure_storage: ^9.2.4

  # Écrans d'introduction et login
  introduction_screen: ^3.1.14
  flutter_login: ^5.0.0
  flutter_otp_text_field: ^1.5.1+1
  otp_text_field: ^1.1.3

  # Communication / HTTP / Messaging
  http: ^1.4.0
  firebase_messaging: ^15.2.5
  url_launcher: ^6.1.7

  # State Management
  provider: ^6.1.2
  get: ^4.7.2

  # Préférences utilisateur
  shared_preferences: ^2.5.3
  lucide_icons: ^0.257.0
  intl: ^0.19.0
  country_code_picker: ^3.3.0
  flutter_multi_formatter: ^2.13.7
  intl_phone_field: ^3.2.0
  otp_text_field_v2: ^1.0.3
  cloud_firestore: ^5.6.6
  flutter_login_facebook: ^2.0.1
  flutter_markdown: ^0.7.7
  device_info_plus: ^11.4.0
  package_info_plus: ^8.3.0
  image_picker: ^1.1.2
  flutter_localization: ^0.3.2
  geoflutterfire_plus: ^0.0.32
  permission_handler: ^12.0.0+1
  file_picker: ^10.1.9
  geolocator: ^14.0.1
  firebase_storage: ^12.4.7
  flutter_map: ^8.1.1
  latlong2: ^0.9.1
  geocoding: ^4.0.0
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true
 
 

  assets:
    - assets/images/
    - assets/logo/
    - assets/icons/
    - assets/fonts/
    - assets/lotties/
    - assets/videos/
    - assets/legal/terms.md
    - assets/legal/privacy.md
